### ISSUE TITLE
problem with GDAL 

### ISSUE THREAD

**Issue by AlexisVM** [Inverdana/Inverdana#2]
Collecting gdal
  Using cached https://files.pythonhosted.org/packages/26/c6/f8846ba726b37f9a1099acb5bff43c309fb913577674c1ba4
91f6fc60598/GDAL-3.0.1.tar.gz
Building wheels for collected packages: gdal
  Building wheel for gdal (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\alexi\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptool
s, tokenize; sys.argv[0] = '"'"'C:\\Users\\alexi\\AppData\\Local\\Temp\\pip-install-1u1looxo\\gdal\\setup.py'"
'"'; __file__='"'"'C:\\Users\\alexi\\AppData\\Local\\Temp\\pip-install-1u1looxo\\gdal\\setup.py'"'"';f=getattr
(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(
compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\alexi\AppData\Local\Temp\pip-wheel-yk_kwq80
' --python-tag cp37
       cwd: C:\Users\alexi\AppData\Local\Temp\pip-install-1u1looxo\gdal\
  Complete output (26 lines):
  WARNING: numpy not available!  Array support will not be enabled
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.7
  copying gdal.py -> build\lib.win32-3.7
  copying ogr.py -> build\lib.win32-3.7
  copying osr.py -> build\lib.win32-3.7
  copying gdalconst.py -> build\lib.win32-3.7
  creating build\lib.win32-3.7\osgeo
  copying osgeo\gdal.py -> build\lib.win32-3.7\osgeo
  copying osgeo\gdalconst.py -> build\lib.win32-3.7\osgeo
  copying osgeo\gdalnumeric.py -> build\lib.win32-3.7\osgeo
  copying osgeo\gdal_array.py -> build\lib.win32-3.7\osgeo
  copying osgeo\gnm.py -> build\lib.win32-3.7\osgeo
  copying osgeo\ogr.py -> build\lib.win32-3.7\osgeo
  copying osgeo\osr.py -> build\lib.win32-3.7\osgeo
  copying osgeo\__init__.py -> build\lib.win32-3.7\osgeo
  Fixing build\lib.win32-3.7\gdal.py build\lib.win32-3.7\ogr.py build\lib.win32-3.7\osr.py build\lib.win32-3.7
\gdalconst.py build\lib.win32-3.7\osgeo\gdal.py build\lib.win32-3.7\osgeo\gdalconst.py build\lib.win32-3.7\osg
eo\gdalnumeric.py build\lib.win32-3.7\osgeo\gdal_array.py build\lib.win32-3.7\osgeo\gnm.py build\lib.win32-3.7
\osgeo\ogr.py build\lib.win32-3.7\osgeo\osr.py build\lib.win32-3.7\osgeo\__init__.py
  Skipping optional fixer: ws_comma
  Fixing build\lib.win32-3.7\gdal.py build\lib.win32-3.7\ogr.py build\lib.win32-3.7\osr.py build\lib.win32-3.7
\gdalconst.py build\lib.win32-3.7\osgeo\gdal.py build\lib.win32-3.7\osgeo\gdalconst.py build\lib.win32-3.7\osg
eo\gdalnumeric.py build\lib.win32-3.7\osgeo\gdal_array.py build\lib.win32-3.7\osgeo\gnm.py build\lib.win32-3.7
\osgeo\ogr.py build\lib.win32-3.7\osgeo\osr.py build\lib.win32-3.7\osgeo\__init__.py
  Skipping optional fixer: ws_comma
  running build_ext
  building 'osgeo._gdal' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visual
studio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for gdal
  Running setup.py clean for gdal
Failed to build gdal
Installing collected packages: gdal
  Running setup.py install for gdal ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\alexi\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setupto
ols, tokenize; sys.argv[0] = '"'"'C:\\Users\\alexi\\AppData\\Local\\Temp\\pip-install-1u1looxo\\gdal\\setup.py
'"'"'; __file__='"'"'C:\\Users\\alexi\\AppData\\Local\\Temp\\pip-install-1u1looxo\\gdal\\setup.py'"'"';f=getat
tr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exe
c(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\alexi\AppData\Local\Temp\pip-record-au1
vd7sg\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\alexi\AppData\Local\Temp\pip-install-1u1looxo\gdal\
    Complete output (26 lines):
    WARNING: numpy not available!  Array support will not be enabled
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    copying gdal.py -> build\lib.win32-3.7
    copying ogr.py -> build\lib.win32-3.7
    copying osr.py -> build\lib.win32-3.7
    copying gdalconst.py -> build\lib.win32-3.7
    creating build\lib.win32-3.7\osgeo
    copying osgeo\gdal.py -> build\lib.win32-3.7\osgeo
    copying osgeo\gdalconst.py -> build\lib.win32-3.7\osgeo
    copying osgeo\gdalnumeric.py -> build\lib.win32-3.7\osgeo
    copying osgeo\gdal_array.py -> build\lib.win32-3.7\osgeo
    copying osgeo\gnm.py -> build\lib.win32-3.7\osgeo
    copying osgeo\ogr.py -> build\lib.win32-3.7\osgeo
    copying osgeo\osr.py -> build\lib.win32-3.7\osgeo
    copying osgeo\__init__.py -> build\lib.win32-3.7\osgeo
    Fixing build\lib.win32-3.7\gdal.py build\lib.win32-3.7\ogr.py build\lib.win32-3.7\osr.py build\lib.win32-3
.7\gdalconst.py build\lib.win32-3.7\osgeo\gdal.py build\lib.win32-3.7\osgeo\gdalconst.py build\lib.win32-3.7\o
sgeo\gdalnumeric.py build\lib.win32-3.7\osgeo\gdal_array.py build\lib.win32-3.7\osgeo\gnm.py build\lib.win32-3
.7\osgeo\ogr.py build\lib.win32-3.7\osgeo\osr.py build\lib.win32-3.7\osgeo\__init__.py
    Skipping optional fixer: ws_comma
    Fixing build\lib.win32-3.7\gdal.py build\lib.win32-3.7\ogr.py build\lib.win32-3.7\osr.py build\lib.win32-3
.7\gdalconst.py build\lib.win32-3.7\osgeo\gdal.py build\lib.win32-3.7\osgeo\gdalconst.py build\lib.win32-3.7\o
sgeo\gdalnumeric.py build\lib.win32-3.7\osgeo\gdal_array.py build\lib.win32-3.7\osgeo\gnm.py build\lib.win32-3
.7\osgeo\ogr.py build\lib.win32-3.7\osgeo\osr.py build\lib.win32-3.7\osgeo\__init__.py
    Skipping optional fixer: ws_comma
    running build_ext
    building 'osgeo._gdal' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visu
alstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\alexi\appdata\local\programs\python\python37-32\pytho
n.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\alexi\\AppData\\Local\\Temp\\pip
-install-1u1looxo\\gdal\\setup.py'"'"'; __file__='"'"'C:\\Users\\alexi\\AppData\\Local\\Temp\\pip-install-1u1l
ooxo\\gdal\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'
"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\alexi\
AppData\Local\Temp\pip-record-au1vd7sg\install-record.txt' --single-version-externally-managed --compile Check
 the logs for full command output.

**Comment by 3t4n** [comment]
Installed with conda
